### ISSUE TITLE
Chain sync crash

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/walletd#204]
### Current Behavior

```
2024-12-13T05:26:32-05:00	INFO	node started	{"syncer": "[::]:9981", "http": "127.0.0.1:9980", "version": "v0.8.0", "commit": "e549203"}
2024-12-13T05:26:32-05:00	PANIC	wallet.sync	failed to sync store	{"error": "failed to subscribe to chain manager: missing block at index 490977::f9b2ba46"}
panic: failed to sync store

goroutine 55 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc00038e080?})
	go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0003b01a0, {0xc0003ac040, 0x1, 0x1})
	go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x24e
go.uber.org/zap.(*Logger).Panic(0x1bcb0c0?, {0xb32c43?, 0x1bcb060?}, {0xc0003ac040, 0x1, 0x1})
	go.uber.org/zap@v1.27.0/logger.go:285 +0x51
go.sia.tech/walletd/wallet.NewManager.func2()
	go.sia.tech/walletd/wallet/manager.go:386 +0x653
created by go.sia.tech/walletd/wallet.NewManager in goroutine 1
	go.sia.tech/walletd/wallet/manager.go:363 +0x399
```

So far I have found it is likely in the sqlite db itself, which is problematic as I cant just delete that without re-importing all accounts. Deleting the consensus db helps none.

### Expected Behavior

Walletd to boot normally with my data

### Version

v0.12.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Linux Mint

**Comment by n8maninger** [comment]
Was there a different panic before you deleted your consensus db?

**Comment by pcfreak30** [comment]
no, not that im aware of. before this panic I was having issues with https://github.com/SiaFoundation/walletd/issues/202.
